/*
全部  API 文档

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zsgf

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendEmailCodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendEmailCodeRequest{}

// SendEmailCodeRequest struct for SendEmailCodeRequest
type SendEmailCodeRequest struct {
	Email string `json:"email"`
	// 用途。可选值：signup/forgetpwd
	Type string `json:"type"`
}

type _SendEmailCodeRequest SendEmailCodeRequest

// NewSendEmailCodeRequest instantiates a new SendEmailCodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendEmailCodeRequest(email string, type_ string) *SendEmailCodeRequest {
	this := SendEmailCodeRequest{}
	this.Email = email
	this.Type = type_
	return &this
}

// NewSendEmailCodeRequestWithDefaults instantiates a new SendEmailCodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendEmailCodeRequestWithDefaults() *SendEmailCodeRequest {
	this := SendEmailCodeRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *SendEmailCodeRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SendEmailCodeRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SendEmailCodeRequest) SetEmail(v string) {
	o.Email = v
}

// GetType returns the Type field value
func (o *SendEmailCodeRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SendEmailCodeRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SendEmailCodeRequest) SetType(v string) {
	o.Type = v
}

func (o SendEmailCodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendEmailCodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SendEmailCodeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendEmailCodeRequest := _SendEmailCodeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendEmailCodeRequest)

	if err != nil {
		return err
	}

	*o = SendEmailCodeRequest(varSendEmailCodeRequest)

	return err
}

type NullableSendEmailCodeRequest struct {
	value *SendEmailCodeRequest
	isSet bool
}

func (v NullableSendEmailCodeRequest) Get() *SendEmailCodeRequest {
	return v.value
}

func (v *NullableSendEmailCodeRequest) Set(val *SendEmailCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendEmailCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendEmailCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendEmailCodeRequest(val *SendEmailCodeRequest) *NullableSendEmailCodeRequest {
	return &NullableSendEmailCodeRequest{value: val, isSet: true}
}

func (v NullableSendEmailCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendEmailCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


