/*
全部  API 文档

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zsgf

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailSignInRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailSignInRequest{}

// EmailSignInRequest struct for EmailSignInRequest
type EmailSignInRequest struct {
	Email string `json:"email"`
	VerifyCode string `json:"verifyCode" validate:"regexp=\\\\d{4,8}$"`
	// 如果启用双因素认证登录，则必填
	TwoFactorCode NullableString `json:"twoFactorCode,omitempty"`
}

type _EmailSignInRequest EmailSignInRequest

// NewEmailSignInRequest instantiates a new EmailSignInRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailSignInRequest(email string, verifyCode string) *EmailSignInRequest {
	this := EmailSignInRequest{}
	this.Email = email
	this.VerifyCode = verifyCode
	return &this
}

// NewEmailSignInRequestWithDefaults instantiates a new EmailSignInRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailSignInRequestWithDefaults() *EmailSignInRequest {
	this := EmailSignInRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *EmailSignInRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailSignInRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailSignInRequest) SetEmail(v string) {
	o.Email = v
}

// GetVerifyCode returns the VerifyCode field value
func (o *EmailSignInRequest) GetVerifyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerifyCode
}

// GetVerifyCodeOk returns a tuple with the VerifyCode field value
// and a boolean to check if the value has been set.
func (o *EmailSignInRequest) GetVerifyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerifyCode, true
}

// SetVerifyCode sets field value
func (o *EmailSignInRequest) SetVerifyCode(v string) {
	o.VerifyCode = v
}

// GetTwoFactorCode returns the TwoFactorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailSignInRequest) GetTwoFactorCode() string {
	if o == nil || IsNil(o.TwoFactorCode.Get()) {
		var ret string
		return ret
	}
	return *o.TwoFactorCode.Get()
}

// GetTwoFactorCodeOk returns a tuple with the TwoFactorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailSignInRequest) GetTwoFactorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TwoFactorCode.Get(), o.TwoFactorCode.IsSet()
}

// HasTwoFactorCode returns a boolean if a field has been set.
func (o *EmailSignInRequest) HasTwoFactorCode() bool {
	if o != nil && o.TwoFactorCode.IsSet() {
		return true
	}

	return false
}

// SetTwoFactorCode gets a reference to the given NullableString and assigns it to the TwoFactorCode field.
func (o *EmailSignInRequest) SetTwoFactorCode(v string) {
	o.TwoFactorCode.Set(&v)
}
// SetTwoFactorCodeNil sets the value for TwoFactorCode to be an explicit nil
func (o *EmailSignInRequest) SetTwoFactorCodeNil() {
	o.TwoFactorCode.Set(nil)
}

// UnsetTwoFactorCode ensures that no value is present for TwoFactorCode, not even an explicit nil
func (o *EmailSignInRequest) UnsetTwoFactorCode() {
	o.TwoFactorCode.Unset()
}

func (o EmailSignInRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailSignInRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["verifyCode"] = o.VerifyCode
	if o.TwoFactorCode.IsSet() {
		toSerialize["twoFactorCode"] = o.TwoFactorCode.Get()
	}
	return toSerialize, nil
}

func (o *EmailSignInRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"verifyCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailSignInRequest := _EmailSignInRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailSignInRequest)

	if err != nil {
		return err
	}

	*o = EmailSignInRequest(varEmailSignInRequest)

	return err
}

type NullableEmailSignInRequest struct {
	value *EmailSignInRequest
	isSet bool
}

func (v NullableEmailSignInRequest) Get() *EmailSignInRequest {
	return v.value
}

func (v *NullableEmailSignInRequest) Set(val *EmailSignInRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailSignInRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailSignInRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailSignInRequest(val *EmailSignInRequest) *NullableEmailSignInRequest {
	return &NullableEmailSignInRequest{value: val, isSet: true}
}

func (v NullableEmailSignInRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailSignInRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


