/*
全部  API 文档

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zsgf

import (
	"encoding/json"
)

// checks if the SettingsApiResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsApiResponse{}

// SettingsApiResponse struct for SettingsApiResponse
type SettingsApiResponse struct {
	// 状态码
	Code *int32 `json:"code,omitempty"`
	Data *Settings `json:"data,omitempty"`
	// 错误信息
	Error NullableString `json:"error,omitempty"`
}

// NewSettingsApiResponse instantiates a new SettingsApiResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsApiResponse() *SettingsApiResponse {
	this := SettingsApiResponse{}
	var code int32 = 200
	this.Code = &code
	var error_ string = ""
	this.Error = *NewNullableString(&error_)
	return &this
}

// NewSettingsApiResponseWithDefaults instantiates a new SettingsApiResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsApiResponseWithDefaults() *SettingsApiResponse {
	this := SettingsApiResponse{}
	var code int32 = 200
	this.Code = &code
	var error_ string = ""
	this.Error = *NewNullableString(&error_)
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SettingsApiResponse) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsApiResponse) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SettingsApiResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *SettingsApiResponse) SetCode(v int32) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SettingsApiResponse) GetData() Settings {
	if o == nil || IsNil(o.Data) {
		var ret Settings
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsApiResponse) GetDataOk() (*Settings, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SettingsApiResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Settings and assigns it to the Data field.
func (o *SettingsApiResponse) SetData(v Settings) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SettingsApiResponse) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingsApiResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *SettingsApiResponse) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *SettingsApiResponse) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *SettingsApiResponse) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *SettingsApiResponse) UnsetError() {
	o.Error.Unset()
}

func (o SettingsApiResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsApiResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	return toSerialize, nil
}

type NullableSettingsApiResponse struct {
	value *SettingsApiResponse
	isSet bool
}

func (v NullableSettingsApiResponse) Get() *SettingsApiResponse {
	return v.value
}

func (v *NullableSettingsApiResponse) Set(val *SettingsApiResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsApiResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsApiResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsApiResponse(val *SettingsApiResponse) *NullableSettingsApiResponse {
	return &NullableSettingsApiResponse{value: val, isSet: true}
}

func (v NullableSettingsApiResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsApiResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


