/*
全部  API 文档

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zsgf

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnionIDSignUpRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnionIDSignUpRequest{}

// UnionIDSignUpRequest struct for UnionIDSignUpRequest
type UnionIDSignUpRequest struct {
	// 登录账号，可空
	UserName NullableString `json:"userName,omitempty"`
	// UnionID
	UnionID string `json:"unionID"`
	// 平台标识
	Platform string `json:"platform"`
	// 密码，6~32位
	Pwd string `json:"pwd" validate:"regexp=^[a-zA-Z0-9_-~!@#$%^&*]{6,32}$"`
	// 昵称
	NickName NullableString `json:"nickName,omitempty"`
	// 头像
	Avatar NullableString `json:"avatar,omitempty"`
	// 自定义数据
	Data NullableString `json:"data,omitempty"`
	// 邮箱
	Email NullableString `json:"email,omitempty" validate:"regexp=^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,5}$"`
	// 邮箱验证码（只有启用的邮箱验证码功能时，才需要传入）
	EmailCode NullableString `json:"emailCode,omitempty" validate:"regexp=\\\\d{4,8}$"`
	// 手机号
	Phone NullableString `json:"phone,omitempty" validate:"regexp=^(\\\\d{11})?$"`
	// 手机验证码（只有启用的手机验证码功能时，才需要传入）
	PhoneCode NullableString `json:"phoneCode,omitempty" validate:"regexp=\\\\d{4,8}$"`
}

type _UnionIDSignUpRequest UnionIDSignUpRequest

// NewUnionIDSignUpRequest instantiates a new UnionIDSignUpRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnionIDSignUpRequest(unionID string, platform string, pwd string) *UnionIDSignUpRequest {
	this := UnionIDSignUpRequest{}
	this.UnionID = unionID
	this.Platform = platform
	this.Pwd = pwd
	return &this
}

// NewUnionIDSignUpRequestWithDefaults instantiates a new UnionIDSignUpRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnionIDSignUpRequestWithDefaults() *UnionIDSignUpRequest {
	this := UnionIDSignUpRequest{}
	return &this
}

// GetUserName returns the UserName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnionIDSignUpRequest) GetUserName() string {
	if o == nil || IsNil(o.UserName.Get()) {
		var ret string
		return ret
	}
	return *o.UserName.Get()
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnionIDSignUpRequest) GetUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserName.Get(), o.UserName.IsSet()
}

// HasUserName returns a boolean if a field has been set.
func (o *UnionIDSignUpRequest) HasUserName() bool {
	if o != nil && o.UserName.IsSet() {
		return true
	}

	return false
}

// SetUserName gets a reference to the given NullableString and assigns it to the UserName field.
func (o *UnionIDSignUpRequest) SetUserName(v string) {
	o.UserName.Set(&v)
}
// SetUserNameNil sets the value for UserName to be an explicit nil
func (o *UnionIDSignUpRequest) SetUserNameNil() {
	o.UserName.Set(nil)
}

// UnsetUserName ensures that no value is present for UserName, not even an explicit nil
func (o *UnionIDSignUpRequest) UnsetUserName() {
	o.UserName.Unset()
}

// GetUnionID returns the UnionID field value
func (o *UnionIDSignUpRequest) GetUnionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnionID
}

// GetUnionIDOk returns a tuple with the UnionID field value
// and a boolean to check if the value has been set.
func (o *UnionIDSignUpRequest) GetUnionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnionID, true
}

// SetUnionID sets field value
func (o *UnionIDSignUpRequest) SetUnionID(v string) {
	o.UnionID = v
}

// GetPlatform returns the Platform field value
func (o *UnionIDSignUpRequest) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *UnionIDSignUpRequest) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *UnionIDSignUpRequest) SetPlatform(v string) {
	o.Platform = v
}

// GetPwd returns the Pwd field value
func (o *UnionIDSignUpRequest) GetPwd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pwd
}

// GetPwdOk returns a tuple with the Pwd field value
// and a boolean to check if the value has been set.
func (o *UnionIDSignUpRequest) GetPwdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pwd, true
}

// SetPwd sets field value
func (o *UnionIDSignUpRequest) SetPwd(v string) {
	o.Pwd = v
}

// GetNickName returns the NickName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnionIDSignUpRequest) GetNickName() string {
	if o == nil || IsNil(o.NickName.Get()) {
		var ret string
		return ret
	}
	return *o.NickName.Get()
}

// GetNickNameOk returns a tuple with the NickName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnionIDSignUpRequest) GetNickNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NickName.Get(), o.NickName.IsSet()
}

// HasNickName returns a boolean if a field has been set.
func (o *UnionIDSignUpRequest) HasNickName() bool {
	if o != nil && o.NickName.IsSet() {
		return true
	}

	return false
}

// SetNickName gets a reference to the given NullableString and assigns it to the NickName field.
func (o *UnionIDSignUpRequest) SetNickName(v string) {
	o.NickName.Set(&v)
}
// SetNickNameNil sets the value for NickName to be an explicit nil
func (o *UnionIDSignUpRequest) SetNickNameNil() {
	o.NickName.Set(nil)
}

// UnsetNickName ensures that no value is present for NickName, not even an explicit nil
func (o *UnionIDSignUpRequest) UnsetNickName() {
	o.NickName.Unset()
}

// GetAvatar returns the Avatar field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnionIDSignUpRequest) GetAvatar() string {
	if o == nil || IsNil(o.Avatar.Get()) {
		var ret string
		return ret
	}
	return *o.Avatar.Get()
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnionIDSignUpRequest) GetAvatarOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Avatar.Get(), o.Avatar.IsSet()
}

// HasAvatar returns a boolean if a field has been set.
func (o *UnionIDSignUpRequest) HasAvatar() bool {
	if o != nil && o.Avatar.IsSet() {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given NullableString and assigns it to the Avatar field.
func (o *UnionIDSignUpRequest) SetAvatar(v string) {
	o.Avatar.Set(&v)
}
// SetAvatarNil sets the value for Avatar to be an explicit nil
func (o *UnionIDSignUpRequest) SetAvatarNil() {
	o.Avatar.Set(nil)
}

// UnsetAvatar ensures that no value is present for Avatar, not even an explicit nil
func (o *UnionIDSignUpRequest) UnsetAvatar() {
	o.Avatar.Unset()
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnionIDSignUpRequest) GetData() string {
	if o == nil || IsNil(o.Data.Get()) {
		var ret string
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnionIDSignUpRequest) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *UnionIDSignUpRequest) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableString and assigns it to the Data field.
func (o *UnionIDSignUpRequest) SetData(v string) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *UnionIDSignUpRequest) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *UnionIDSignUpRequest) UnsetData() {
	o.Data.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnionIDSignUpRequest) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnionIDSignUpRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *UnionIDSignUpRequest) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *UnionIDSignUpRequest) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *UnionIDSignUpRequest) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *UnionIDSignUpRequest) UnsetEmail() {
	o.Email.Unset()
}

// GetEmailCode returns the EmailCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnionIDSignUpRequest) GetEmailCode() string {
	if o == nil || IsNil(o.EmailCode.Get()) {
		var ret string
		return ret
	}
	return *o.EmailCode.Get()
}

// GetEmailCodeOk returns a tuple with the EmailCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnionIDSignUpRequest) GetEmailCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmailCode.Get(), o.EmailCode.IsSet()
}

// HasEmailCode returns a boolean if a field has been set.
func (o *UnionIDSignUpRequest) HasEmailCode() bool {
	if o != nil && o.EmailCode.IsSet() {
		return true
	}

	return false
}

// SetEmailCode gets a reference to the given NullableString and assigns it to the EmailCode field.
func (o *UnionIDSignUpRequest) SetEmailCode(v string) {
	o.EmailCode.Set(&v)
}
// SetEmailCodeNil sets the value for EmailCode to be an explicit nil
func (o *UnionIDSignUpRequest) SetEmailCodeNil() {
	o.EmailCode.Set(nil)
}

// UnsetEmailCode ensures that no value is present for EmailCode, not even an explicit nil
func (o *UnionIDSignUpRequest) UnsetEmailCode() {
	o.EmailCode.Unset()
}

// GetPhone returns the Phone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnionIDSignUpRequest) GetPhone() string {
	if o == nil || IsNil(o.Phone.Get()) {
		var ret string
		return ret
	}
	return *o.Phone.Get()
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnionIDSignUpRequest) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phone.Get(), o.Phone.IsSet()
}

// HasPhone returns a boolean if a field has been set.
func (o *UnionIDSignUpRequest) HasPhone() bool {
	if o != nil && o.Phone.IsSet() {
		return true
	}

	return false
}

// SetPhone gets a reference to the given NullableString and assigns it to the Phone field.
func (o *UnionIDSignUpRequest) SetPhone(v string) {
	o.Phone.Set(&v)
}
// SetPhoneNil sets the value for Phone to be an explicit nil
func (o *UnionIDSignUpRequest) SetPhoneNil() {
	o.Phone.Set(nil)
}

// UnsetPhone ensures that no value is present for Phone, not even an explicit nil
func (o *UnionIDSignUpRequest) UnsetPhone() {
	o.Phone.Unset()
}

// GetPhoneCode returns the PhoneCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnionIDSignUpRequest) GetPhoneCode() string {
	if o == nil || IsNil(o.PhoneCode.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneCode.Get()
}

// GetPhoneCodeOk returns a tuple with the PhoneCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnionIDSignUpRequest) GetPhoneCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneCode.Get(), o.PhoneCode.IsSet()
}

// HasPhoneCode returns a boolean if a field has been set.
func (o *UnionIDSignUpRequest) HasPhoneCode() bool {
	if o != nil && o.PhoneCode.IsSet() {
		return true
	}

	return false
}

// SetPhoneCode gets a reference to the given NullableString and assigns it to the PhoneCode field.
func (o *UnionIDSignUpRequest) SetPhoneCode(v string) {
	o.PhoneCode.Set(&v)
}
// SetPhoneCodeNil sets the value for PhoneCode to be an explicit nil
func (o *UnionIDSignUpRequest) SetPhoneCodeNil() {
	o.PhoneCode.Set(nil)
}

// UnsetPhoneCode ensures that no value is present for PhoneCode, not even an explicit nil
func (o *UnionIDSignUpRequest) UnsetPhoneCode() {
	o.PhoneCode.Unset()
}

func (o UnionIDSignUpRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnionIDSignUpRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.UserName.IsSet() {
		toSerialize["userName"] = o.UserName.Get()
	}
	toSerialize["unionID"] = o.UnionID
	toSerialize["platform"] = o.Platform
	toSerialize["pwd"] = o.Pwd
	if o.NickName.IsSet() {
		toSerialize["nickName"] = o.NickName.Get()
	}
	if o.Avatar.IsSet() {
		toSerialize["avatar"] = o.Avatar.Get()
	}
	if o.Data.IsSet() {
		toSerialize["data"] = o.Data.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.EmailCode.IsSet() {
		toSerialize["emailCode"] = o.EmailCode.Get()
	}
	if o.Phone.IsSet() {
		toSerialize["phone"] = o.Phone.Get()
	}
	if o.PhoneCode.IsSet() {
		toSerialize["phoneCode"] = o.PhoneCode.Get()
	}
	return toSerialize, nil
}

func (o *UnionIDSignUpRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unionID",
		"platform",
		"pwd",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnionIDSignUpRequest := _UnionIDSignUpRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnionIDSignUpRequest)

	if err != nil {
		return err
	}

	*o = UnionIDSignUpRequest(varUnionIDSignUpRequest)

	return err
}

type NullableUnionIDSignUpRequest struct {
	value *UnionIDSignUpRequest
	isSet bool
}

func (v NullableUnionIDSignUpRequest) Get() *UnionIDSignUpRequest {
	return v.value
}

func (v *NullableUnionIDSignUpRequest) Set(val *UnionIDSignUpRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnionIDSignUpRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnionIDSignUpRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnionIDSignUpRequest(val *UnionIDSignUpRequest) *NullableUnionIDSignUpRequest {
	return &NullableUnionIDSignUpRequest{value: val, isSet: true}
}

func (v NullableUnionIDSignUpRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnionIDSignUpRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


